### ISSUE TITLE
[BUG]  OSError: [Errno 16] Resource busy: '/var/log/qsp-protocol/qsp-protocol.log'

### ISSUE THREAD

**Issue by quarnage** [quantstamp/qsp-protocol-node#552]
Node seems to work fine for approximately 2 days, then starts to display this error.
restart the node and same behavior.

## Steps to Reproduce

1. Start node
2. wait couple days
3. never answer contract requests.
4.

## Your Environment
Docker version 17.09.1-ce, build e398b97

CONTAINER CPU % MEM USAGE / LIMIT MEM % NET I/O BLOCK I/O PIDS
5063e2b5958c 1.55% 43.71MiB / 15.56GiB 0.27% 30MB / 8.67MB 1.31MB / 0B 0

Linux version 4.2.8

Running on - QNAP 453A NAS

## Additional Comments

FULL MESSAGE,

--- Logging error ---                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                               
  File "/usr/lib/python3.6/logging/handlers.py", line 72, in emit                                                                                                                                
    self.doRollover()                                                                                                                                                                            
  File "/usr/lib/python3.6/logging/handlers.py", line 173, in doRollover                                                                                                                         
    self.rotate(self.baseFilename, dfn)                                                                                                                                                          
  File "/usr/lib/python3.6/logging/handlers.py", line 113, in rotate                                                                                                                             
    os.rename(source, dest)            
OSError: [Errno 16] Resource busy: '/var/log/qsp-protocol/qsp-protocol.log' -> '/var/log/qsp-protocol/qsp-protocol.log.1'                                                                        
Call stack:                                                                                                                                                                                      
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap                                                                                                                                
    self._bootstrap_inner()                                                                                                                                                                      
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                                                          
    self.run()                                                                                                                                                                                   
  File "/app/src/qsp_protocol_node/audit/threads/qsp_thread.py", line 124, in run                                                                                                                
    self._target_function(current_block)                                                                                                                                                         
  File "/app/src/qsp_protocol_node/audit/threads/compute_gas_price_thread.py", line 21, in __on_block_mined                                                                                      
    str(block_number), str(self.config.gas_price_wei)))                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/structlog/stdlib.py", line 61, in debug                                                                                                                 
    return self._proxy_to_logger("debug", event, *args, **kw)                                                                                                                                    
  File "/usr/lib/python3.6/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger                                                                                                     
    **event_kw)                                                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/structlog/_bas

**Comment by mderka** [comment]
Hi, thank you for opening the issue. Can you please confirm that the volume mounted to /var/log has enough free space and that the log files are not open in another program that could be holding a lock, e.g., vim?

**Comment by jalme** [comment]
Hi,

The wallet needed QSP tokens before submitting the transaction. After doing that it went through correctly.

All fixed.

Thanks,
João
